### ISSUE TITLE
Понять какие нужны методы логики

### ISSUE THREAD

**Issue by OptimumDev** [742PM/soc.io#3]
- [x] - Расписать методы для интерфейсов логики

**Comment by OptimumDev** [comment]
1. Выдать человеку собеседника - я передаю какой-то идентификатор, человеку назначается случайный собеседник:
   - В случае отсутствия свободных собеседников, человек попадает в некую комнату ожидания, где он сидит пока его не вытащат как собеседника либо он сам не выйдет + надо как-то вернуть признак того что такое случилось из метода (возможно bool - назначили / не назначили)
   - Желательно не назначать челу одно и того же собеседника подряд (возможно несколько последних)
2. Получить собеседника - для переправки сообщений между ними
3. Убрать человека из ожидания общения
4. Изменить собеседника - по сути первый пункт для каждого
5. Закончить общение - для собеседника выполняем первый пункт

По моим прикидкам, этого должно быть достаточно и такой вариант позволит жить без сохранения состояния и без фонового процесса который мог бы назначать собеседников из очереди. НО это все только из головы, когда начнем писать код наверняка всплывут проблемы.

Надо будет подумать, что делать с асинхронностью, в теории два человека могут одновременно запросить собеседника и хер че с этим сделаешь. Кажется тут кроме как синхроинть все, мало что можно еще сделать, так что может вариант со списком-очередью на общение и фоновым процессом который будет им управлять не так уж и плох. @FunFunFine тут хочу узнать твое мнение, можем обсудить реализицю обоих вариантов

Есть идейка как реализовать текущий вариант: в бд список пользователей которые хотят общаться: некий идентификатор + идентификатор собеседника. Таким образом при назначении можно будет искать в этом списке у кого собеседник null, при ожидании - запихивать туда с null собеседником, при выходе из общения удалять из этого списка.  
Если захотим, можно сделать админскую ручку для получения числа текущих людей которые общаются и ждут собеседника.

Еще момент, почему разделил 3 и 5 пункты, они ведь кажется похожи: в голове случились жесткие траблы с тем как обрабатывать результат выполнения. Я даже объяснить не могу, просто на подсознательном уровне кажется что так лучше.

**Comment by FunFunFine** [comment]
```
class QueueManager: 
  PutHumanInQueue
  RemoveHumanFromQueue

class ConversationManager(QueueManager):
  StopDialog //из системы выкинуть тебя,  а собеседника в очередь
  ChangeHuman
  StartDialog
  GetCurrentHumanInfo: TelegramStuff

```
  
  
Таблица для очереди:
```
| юзерид |
```
таблица для метаинфы о диалогах:
```
| собеседник1 | собеседник2 | датавремя начала диалога | датавремя конца диалога |
```
