### ISSUE TITLE
Реализовать репозитории БД

### ISSUE THREAD

**Issue by OptimumDev** [742PM/soc.io#8]

**Comment by FunFunFine** [comment]
## Общее
* Сделать папочку resources, в которую положить файлик с описанием БД — DDL создание таблиц блаблабла как [тут](https://github.com/romutchio/docs.github.io/blob/master/backend/src/main/resources/schema-postgres.sql)
* Подключить либу для работы с постгрей? 

## Реализовать `queue.QueueRepository`
Репозиторий для оч простой таблицы:
```
| userId : String |
```
и реализовать методы
```kotlin
fun put(userId: UserId): Void
fun remove(userId: UserId): Void
fun contains(userId: UserId): Boolean
fun all: List<UserId> 
```

## Реализовать `conversation.ConversationRepository`
Репозиторий для таблицы с метаинформацией о диалогах.
```
 | conversation_id | user1_id : string | user2_id : string | startedAt : datetimetz not null | endedAt : datetimetz can be null |
```
Реализовать методы:
```kotlin
    fun insert(info: ConversationInfo): ConversationId
    fun find(id: ConversationId): ConversationInfo?
    fun all(): List<Conversation>
    fun findForUser(userId: UserId): Conversation?
```
типчики там уже написаны все.

**Comment by OptimumDev** [comment]
1. Почему в одном случае put, а во втором insert?
2. Я не уверен что в случае с [Либой для котлина](https://github.com/JetBrains/Exposed) надо описывать таблицы в resources, там вроде свой вариант

**Comment by FunFunFine** [comment]
> Почему в одном случае put, а во втором insert?
Потому что типа пут про "временно положить, чтобы потом пут аут", а инсерт — вставить навсегда, удалять ведь не планируем
